### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by ranjanngc** [telerik/kendo-vue#185]
**Describe the bug**
In unit test (vue CLI), while executing a test getting error - `jQuery is not defined`

**To Reproduce**
Write a unit test :
```
import { expect } from 'chai'
import { shallowMount } from '@vue/test-utils'
import frontendInput from '@/controls/input/multiselect.vue'
import Vue from 'vue'

describe('asi-multiselect', () => {
  it('renders with default props', () => {
    //Arrange
    const wrapper = shallowMount(frontendInput)
    //Act - Not Needed
    //Assert
    expect(wrapper.find('.form-group')).exist;
    expect(wrapper.find('.k-multiselect')).exist;
    
  });
}
```

**Expected behavior**
Test should run with pass remark

**Additional context**

Full error log:
  ```
 RUNTIME EXCEPTION  Exception occurred while loading your tests

ReferenceError: jQuery is not defined
    at Object.jquery (D:\app\\src\frontend-control-library\dist\js\webpack:\external "jQuery":1:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at Object.1051 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.core.js:65:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.core.js:21:1)
    at Object.1103 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.core.js:4986:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.core.js:21:1)
    at Object.0 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.core.js:49:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.core.js:21:1)
    at D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.core.js:41:1
    at Object../node_modules/@progress/kendo-ui/js/kendo.core.js (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.core.js:44:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at Object.1042 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.data.js:65:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.data.js:21:1)
    at D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.data.js:73:1
    at Object.1104 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.data.js:74:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.data.js:21:1)
    at Object.0 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.data.js:49:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.data.js:21:1)
    at D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.data.js:41:1
    at Object../node_modules/@progress/kendo-ui/js/kendo.data.js (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.data.js:44:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at Object.1061 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.list.js:72:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.list.js:21:1)
    at D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.list.js:80:1
    at Object.1295 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.list.js:81:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.list.js:21:1)
    at Object.0 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.list.js:49:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.list.js:21:1)
    at D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.list.js:41:1
    at Object../node_modules/@progress/kendo-ui/js/kendo.list.js (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.list.js:44:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at Object.1070 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.multiselect.js:65:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.multiselect.js:21:1)
    at D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.multiselect.js:87:1  
    at Object.1343 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.multiselect.js:88:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.multiselect.js:21:1)
    at Object.0 (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.multiselect.js:49:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.multiselect.js:21:1)
    at D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.multiselect.js:41:1  
    at Object../node_modules/@progress/kendo-ui/js/kendo.multiselect.js (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\@progress\kendo-ui\js\kendo.multiselect.js:44:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at Object../node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/@vue/cli-plugin-typescript/node_modules/ts-loader/index.js?!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/controls/input/multiselect.vue?vue&type=script&lang=ts& (D:\app\\src\frontend-control-library\dist\js\webpack:\src\controls\input\multiselect.vue:19:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at Module../src/controls/input/multiselect.vue?vue&type=script&lang=ts& (D:\app\\src\frontend-control-library\dist\js\webpack:\src\controls\input\multiselect.vue?6a1b:1:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at Module../src/controls/input/multiselect.vue (D:\app\\src\frontend-control-library\dist\js\webpack:\src\controls\input\multiselect.vue?f9c2:1:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at Object../tests/unit/multiselect.spec.ts (D:\app\\src\frontend-control-library\dist\js\webpack:\tests\unit\multiselect.spec.ts:7:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at run (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\mochapack\lib\entry.js:3:1)
    at Array.forEach (<anonymous>)
    at Object../node_modules/mochapack/lib/entry.js (D:\app\\src\frontend-control-library\dist\js\webpack:\node_modules\mochapack\lib\entry.js:10:1)
    at __webpack_require__ (D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:19:1)
    at D:\app\\src\frontend-control-library\dist\js\webpack:\webpack\bootstrap:83:1
    at Object.<anonymous> (D:\app\\src\frontend-control-library\dist\js\main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.module_1.default._extensions.<computed> [as .js] (D:\app\\src\frontend-control-library\node_modules\mochapack\src\util\registerRequireHook.ts:106:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at D:\app\\src\frontend-control-library\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\app\\src\frontend-control-library\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (D:\app\\src\frontend-control-library\node_modules\mocha\lib\mocha.js:809:10)
    at D:\app\\src\frontend-control-library\node_modules\mochapack\src\runner\TestRunner.ts:105:23
    at D:\app\\src\frontend-control-library\node_modules\mochapack\src\webpack\compiler\registerReadyCallback.ts:14:7      
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\app\\src\frontend-control-library\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:63:1)
    at AsyncSeriesHook.lazyCompileHook (D:\app\\src\frontend-control-library\node_modules\tapable\lib\Hook.js:154:20)      
    at D:\app\\src\frontend-control-library\node_modules\webpack\lib\Compiler.js:304:22
    at Compiler.emitRecords (D:\app\\src\frontend-control-library\node_modules\webpack\lib\Compiler.js:499:39)
    at D:\app\\src\frontend-control-library\node_modules\webpack\lib\Compiler.js:298:10
    at D:\app\\src\frontend-control-library\node_modules\webpack\lib\Compiler.js:485:14
    at eval (eval at create (D:\app\\src\frontend-control-library\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at D:\app\\src\frontend-control-library\node_modules\copy-webpack-plugin\dist\index.js:115:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\app\\src\frontend-control-library\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (D:\app\\src\frontend-control-library\node_modules\tapable\lib\Hook.js:154:20)      
    at D:\app\\src\frontend-control-library\node_modules\webpack\lib\Compiler.js:482:27
    at D:\app\\src\frontend-control-library\node_modules\neo-async\async.js:2818:7
    at done (D:\app\\src\frontend-control-library\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\app\\src\frontend-control-library\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at D:\app\\src\frontend-control-library\node_modules\webpack\lib\Compiler.js:464:33
    at MemoryFileSystem.writeFile (D:\app\\src\frontend-control-library\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)
    at writeOut (D:\app\\src\frontend-control-library\node_modules\webpack\lib\Compiler.js:462:30)
    at Immediate._onImmediate (D:\app\\src\frontend-control-library\node_modules\memory-fs\lib\MemoryFileSystem.js:288:4)  
    at processImmediate (internal/timers.js:461:21)

 ERROR  mochapack exited with code 1.
npm ERR! Test failed.  See above for more details.
  ```

**Comment by zdravkov** [comment]
From the provided information it is not clear what is causing the issue. It seems like you are using[ Kendo UI for Vue Wrappers](https://www.telerik.com/kendo-vue-ui/components/dropdowns-wrapper/multiselect/)  that depend on jQuery. If you want to avoid this dependancy you may consider using the native Kendo UI components and our [Native Vue Multiselect component ](https://www.telerik.com/kendo-vue-ui/components/dropdowns/multiselect/)that don't depend on jQuery. 
If you still prefer to use the wrappers you will need to include the jQuery globally so that the test library could find it. 

If you still have questions please share some simple repo where we can replicate the issue so we could be more helpful.

Greetings,
Plamen
