### ISSUE TITLE
Allow numbers as values in multiselect

### ISSUE THREAD

**Issue by zdravkov** [telerik/kendo-vue#197]
**Describe the bug**
```
<multiselect
        :data-items="values"
        :value="values"
      ></multiselect>
...
data() {
    return {
      values: [2,3],
    };
```

select and item
error:

> At TagList.js:81
> Uncaught (in promise) TypeError: tagData.text.replace is not a function
>     at Proxy.eval (TagList.js:81:48)
>     at Array.map (<anonymous>)
>     at Proxy.render (TagList.js:75:19)
>     at renderComponentRoot (runtime-core.esm-bundler.js:623:44)
>     at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:4372:57)
>     at ReactiveEffect.run (reactivity.esm-bundler.js:195:29)
>     at setupRenderEffect (runtime-core.esm-bundler.js:4498:9)
>     at mountComponent (runtime-core.esm-bundler.js:4281:9)
>     at processComponent (runtime-core.esm-bundler.js:4239:17)
>     at patch (runtime-core.esm-bundler.js:3843:21)

**Comment by zdravkov** [comment]
fixed in *3.00 - https://stackblitz.com/edit/zp3gug?file=src/main.vue
